### ISSUE TITLE
'Headers is not defined' error when executing Storyblok commands

### ISSUE THREAD

**Issue by julianollivieira** [storyblok/storyblok-cli#61] opened 2023-07-13 12:47 UTC
**Current behavior:**
`X An error ocurred to listing spaces: Headers is not defined` when executing `storyblok spaces` or `storyblok pull-components` using the latest version (`3.25.0`).

**Expected behavior:**
No errors

**Steps to reproduce:**
Use storyblok-cli version `3.25.0` and execute `storyblok spaces` and `storyblok pull-components`
Observe the error

**Comment by plckr** [comment] 2023-07-14 08:34
I'm with the same problem. I even installed `isomorphic-fetch` because of [this](https://www.storyblok.com/faq/headers-not-defined-storyblok-sdk) but the error persists

**Comment by keichinger** [comment] 2023-07-17 11:31
Can confirm the same issue on my side. Downgrading to v3.24.2 worked.

**Comment by royvou** [comment] 2023-07-18 17:36
Issue is related to the last version of storyblok-js-client which either requires native fetch support in node (node 18 or later) or a pollyfill.

I have created a bump in the required node version as a fix. We should consider adding tests for more node versions if we want to support this.

**Comment by zarxor** [comment] 2023-07-28 12:52
Can also confirm this issue, when trying to pull components through CLI. Running node@18.17.0 and storyblok@3.25.0.

![image](https://github.com/storyblok/storyblok-cli/assets/4263518/fcebdc12-d133-4471-a58e-9f8866aaaf21)

Downgrading to storyblok@3.24.2 solved the issue

**Comment by dariusrosendahl** [comment] 2023-08-08 05:05
Last night I thought I finally upgrade to the latest version and now I have the same problem.

Alright the problem is that you need to run node@18.x 

#62 should be merged so people don't spend 20 minutes trying to figure out what's wrong.. 

@ademarCardoso ?

**Closed as completed** 2023-08-08 17:57 UTC
Labels: bug, released

**Comment by dariusrosendahl** [comment] 2023-08-09 08:07
Thank you so much for your fast response @ademarCardoso ! Liking Storyblok more and more 😁

**Comment by jshrssll** [comment] 2024-06-12 23:33
This is still broken in 3.32.1
